version: "3.8"

services:
  dev:
    container_name: maya-email-dashboard-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8889:8081"

  prod:
    container_name: maya-energy-dashboard-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8888:8888"
    restart: always
 
