version: '3.8'

services:
  dev:
    container_name: maya-energy-dashboard-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '8888:8888'


  prod:
    container_name: maya-energy-dashboard-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '8888:8888'




